Bumping ember-cli-babel
nickiaconis/ember-prefetch pull request #107
Opened 2018-08-27 21:44 UTC by arthirm

2018-09-05 18:32 UTC, rwjblue requested changes

2018-09-05 18:32 UTC, rwjblue commented on package.json
> +    "ember-cli-babel": "6.17.0"
Can you add a `^` here please?

2018-09-05 23:56 UTC, arthirm commented
@rwjblue Updated please check

2018-09-10 13:19 UTC, rwjblue approved these changes

2018-09-10 13:19 UTC, merged

2018-09-11 16:48 UTC, arthirm commented
@rwjblue Can you please release a new version?

2018-09-13 16:53 UTC, arthirm commented
@nickiaconis Can you please release a new version for this?